# Fix for `XF86AudioRaiseVolume` and `XF86AudioLowerVolume` button being handled twice
device {
  name = gpio-keys
  enabled = false
}

device {
  name = gpio-keys-1
  enabled = false
}

device {
  name = video-bus
  enabled = false
}

