plugin {
    hyprexpo {
        columns = 3
        gap_size = 12
        bg_col = rgb(181818)
        workspace_method = first 1
        skip_empty = false
        gesture_distance = 300
    }
}

bindd = SUPER, R, hyprexpo overview, hyprexpo:expo, toggle

gestures {
    hyprexpo-gesture = 3, vertical, expo
}
