workspace = special:scratchpad, layout:scrolling

# windowrule = match:class ^(.*)$, center on

# QQ
windowrule {
    name = QQ
    match:initial_title = ^(QQ)$
    float = on
    center = on
    size = 1200 800
}
windowrule = match:initial_class ^(QQ)$, float true

# wechat
windowrule {
    name = QQ
    match:initial_title = ^(QQ)$
    float = on
    center = on
    size = 1200 800
}

# Bitwarden
windowrule = match:initial_class ^(Bitwarden)$, center on
windowrule = match:initial_class ^(Bitwarden)$, float true
windowrule = match:class ^(Bitwarden)$, tag -floating-window
windowrule = match:initial_class ^(Bitwarden)$, size 1200 800

# localsend
windowrule {
    name = localsend
    match:initial_class = ^(localsend)$
    float = on
    center = on
    size = 800 600
}

# AmneziaVPN
windowrule {
    name = AmneziaVPN
    match:initial_class = ^(AmneziaVPN)$
    float = on
    center = on
    size = 400 800
}

# gnome boxes
windowrule {
    name = org.gnome.Boxes
    match:initial_class = ^(org.gnome.Boxes)$
    float = on
    center = on
    size = 1200 800
}

# Mattermost
windowrule {
    name = Mattermost.Desktop
    match:initial_class = ^(Mattermost.Desktop)$
    float = on
    center = on
    size = 1200 800
}

# pamac manager
windowrule {
    name = org.manjaro.pamac.manager
    match:initial_class = ^(org.manjaro.pamac.manager)$
    float = on
    center = on
    size = 1200 800
}
